### ISSUE TITLE
Fetch distance and get carbon footprint

### ISSUE THREAD

**Issue by susiejojo** [MLH-Fellowship/VehiCO#11]
## Task(s)
- [x] fetch distance between start and end points using OSM API/ Leaflet

- [x] call the endpoint when the maps page is loaded

- [x] Send the distance with correct units and travel mode to TriptoCarbon API

- [x] Return the carbon footprint for the route

## Acceptance Criteria

The carbon footprint value should be returned by the API endpoint and sent to the sidebar for display.

## Dependencies
 #9, #10 

## Resources

- https://triptocarbon.com/documentation/api/footprint
- https://help.openstreetmap.org/questions/37861/distance-matrix-api
