### ISSUE TITLE
Sidebar displaying Trip Report

### ISSUE THREAD

**Issue by cqvu** [MLH-Fellowship/VehiCO#12]
## Task(s)
- [ ] Create a sidebar next to the rendered map
- [ ] Display distance and duration of route from API
- [ ] Display carbon footprint data returned from API #11
- [ ] Render Get Directions button with Google Maps redirect

## Acceptance Criteria

Sidebar displaying trip report including distance, duration, and CO2 emission
Refer to #4 for design

## Dependencies

#11

## Resources

#4 for design mockup
