### ISSUE TITLE
Sidebar displaying carbon footprint stats & offset info

### ISSUE THREAD

**Issue by cqvu** [MLH-Fellowship/VehiCO#13]
## Task(s)
- [ ] Create a sidebar next to the rendered map
- [ ] Display carbon footprint data returned from API #11
- [ ] Display neutralize offset information with donate button that redirects to donation page (for now)

## Acceptance Criteria

Sidebar displaying carbon footprint data and offset info with donate button

## Dependencies

#11

## Resources

N/A
