### ISSUE TITLE
Change transportation mode from Tabbar

### ISSUE THREAD

**Issue by susiejojo** [MLH-Fellowship/VehiCO#18]
## Task(s)

- [ ] Adjust vehicle icons to fit the tab bar.

- [ ] Send the travel mode data to the Routing API (GraphHopper for now) in `RoutingMachine.js`

- [ ] Send the mode, origin, and destination latlng values to the server at `/api` endpoint as query parameters.

- [ ] Return the response fetched from the endpoint and render the carbon footprint, distance and time values on the sidebar.

- [ ] Send the carbon footprint to the bar graph on the sidebar.

- [ ] Allow switching between travel modes and displaying the changed distance, time and carbon footprint values as well as route.

- [ ] (if possible) Cache the response to prevent multiple calls to the APIs.

## Acceptance Criteria

The user should be able to switch between various travel modes from the buttons and see changes on the sidebar and the change in map routes.

## Dependencies

#11, #12
