### ISSUE TITLE
Display Map on Main Dashboard

### ISSUE THREAD

**Issue by cqvu** [MLH-Fellowship/VehiCO#9]
## Task(s)
- [x] Render a Map on the Main Dashboard
- [x] Draw markers for start and end locations
- [x] Draw a default route between the two markers (default car)

## Acceptance Criteria

Map rendered on main dashboard with markers for starting and destination locations as well as a default route

## Dependencies

#4 #10

## Resources

- https://react-leaflet.js.org/
